CREATE TABLE IF NOT EXISTS tmp_course_data_teacher_field_ll (
	semester	varchar(4),
	course_no	varchar(5),
	course_name	varchar(255),
	course_type	varchar(10),
	course_room	varchar(20),
	course_building	varchar(20),
	course_time	varchar(20),
	course_credit	INTEGER,
	course_limit	INTEGER,
	course_status	varchar(10),
	teacher_name	varchar(20),
	student_name	varchar(20),
	student_dept	varchar(30),
	student_grade	INTEGER,
	student_status	varchar(10),
	curriculum_field	TEXT,
	student_class	varchar(1),
	select_result	varchar(10),
	course_score	decimal(4,1),
	feedback_rank	INTEGER
);
CREATE TABLE IF NOT EXISTS tmp_course_data_teacher_field_lr (
	semester	varchar(4),
	course_no	varchar(5),
	course_name	varchar(255),
	course_type	varchar(10),
	course_room	varchar(20),
	course_building	varchar(20),
	course_time	varchar(20),
	course_credit	INTEGER,
	course_limit	INTEGER,
	course_status	varchar(10),
	teacher_name	varchar(20),
	student_name	varchar(20),
	student_dept	varchar(30),
	student_grade	INTEGER,
	student_status	varchar(10),
	curriculum_field	TEXT,
	student_class	varchar(1),
	select_result	varchar(10),
	course_score	decimal(4,1),
	feedback_rank	INTEGER
);
CREATE TABLE IF NOT EXISTS tmp_course_data_teacher_field_rl (
	semester	varchar(4),
	course_no	varchar(5),
	course_name	varchar(255),
	course_type	varchar(10),
	course_room	varchar(20),
	course_building	varchar(20),
	course_time	varchar(20),
	course_credit	INTEGER,
	course_limit	INTEGER,
	course_status	varchar(10),
	teacher_name	varchar(20),
	student_name	varchar(20),
	student_dept	varchar(30),
	student_grade	INTEGER,
	student_status	varchar(10),
	curriculum_field	TEXT,
	student_class	varchar(1),
	select_result	varchar(10),
	course_score	decimal(4,1),
	feedback_rank	INTEGER
);
CREATE TABLE IF NOT EXISTS tmp_course_data_teacher_field_rr (
	semester	varchar(4),
	course_no	varchar(5),
	course_name	varchar(255),
	course_type	varchar(10),
	course_room	varchar(20),
	course_building	varchar(20),
	course_time	varchar(20),
	course_credit	INTEGER,
	course_limit	INTEGER,
	course_status	varchar(10),
	teacher_name	varchar(20),
	student_name	varchar(20),
	student_dept	varchar(30),
	student_grade	INTEGER,
	student_status	varchar(10),
	curriculum_field	TEXT,
	student_class	varchar(1),
	select_result	varchar(10),
	course_score	decimal(4,1),
	feedback_rank	INTEGER
);